name = "The Boglers"
author = "Anton"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec8b957c0aa42eab805e94b07ee6bc214f42ede8dfbe689ec270f5d710c72b2e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.220"
