name = "The Boglers"
author = "Anton"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5dceb37dbe9fc17bc3574a5fd3d6aa390022265302516ed808f1f256b0f79ef"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.221"
